title: 김광민 블로그
email: cocomo1316@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  kyle-log

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5
